name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
        
jobs:
    build:
        runs-on: ubuntu-latest 
        
        steps:
        
        - name: Set up Go 1.x 
          uses: actions/setup-go@v2
          with:
            go-version: ^1.20.3
                        
        - name: Check out code into the Go module directory
          uses: actions/checkout@v2
          
        - name: Build
          run: make build
          
        - name: Copy Files
          run: |
            mkdir artifacts
            cp api artifacts/.
            
        - name: Archive
          uses: actions/upload-artifact@v2
          with:
            name: api
            path: artifacts
