#!/bin/sh
STAGED_GO_FILES=$(git diff --cached --name-only -- '*.go') ❶
if [[ $STAGED_GO_FILES == "" ]]; then ❷
 echo "no go files updated"
else
 for file in $STAGED_GO_FILES; do
 go fmt $file ❸
 git add $file
 done
fi
golang-ci run